// Reference-geometry regression.
//
// This is the replacement for the pinned Hearth test that compared the
// generated tray against `systainer_tray_1_1u_caps.stl` in a specific
// developer's OneDrive folder. That file is not in the repository and not ours
// to redistribute, so the suite either skipped or passed depending on the
// machine. The fixture here is generated by ShapePilot from its own pipeline
// and is checked in, so the same regression is caught everywhere.
import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import { test } from 'vitest'
import { buildTrayMesh } from '../../src/features/keycap-tray/geometry/layers.ts'
import { checkManifold } from '../../src/geometry/mesh.ts'
import { PYTHON_SIZING } from '../../src/features/keycap-tray/geometry/shapes.ts'
import { QUANTUM } from '../../src/geometry/vec.ts'
import { writeBinaryStl } from '../../src/export/stl.ts'
import type { Pocket, TrayDesign } from '../../src/features/keycap-tray/model/types.ts'
import fixture from '../fixtures/reference/systainer-75-pocket.json' with { type: 'json' }

const design = (pockets: Pocket[], over: Partial<TrayDesign> = {}): TrayDesign => ({
  id: 't', name: 'Test tray',
  profile: { kind: 'rect', widthMm: 100, heightMm: 80 },
  sizing: { ...PYTHON_SIZING },
  floorThicknessMm: 2.4, pocketDepthMm: 10, engraveDepthMm: 0.4,
  pockets, revision: 0, ...over,
})

/** The reference tray: 248 x 156 mm, 75 pockets of 18.80 mm on a 12-column grid. */
export function systainerTray(): TrayDesign {
  const pockets: Pocket[] = []
  const pitch = 20.6, cols = 12, rows = 7
  let i = 0
  for (let r = 0; r < rows && i < 75; r++) {
    for (let c = 0; c < cols && i < 75; c++, i++) {
      pockets.push({ id: `p${i}`, units: 1, x: 3.5 + c * pitch, y: 3.5 + r * pitch })
    }
  }
  return design(pockets, { profile: { kind: 'preset', id: 'systainer-s76-plain' } })
}

/**
 * Quantized, order-independent vertex-set hash. Triangle order depends on
 * earcut's fan choices and raw coordinates depend on the platform's
 * Math.cos/Math.sin, so hashing the raw buffer would be flaky. Snapping to the
 * pipeline's own QUANTUM (1e-4 mm) is nine orders of magnitude above that noise.
 */
function vertexSetHash(positions: Float32Array): string {
  const q = (v: number) => Math.round(v / QUANTUM)
  const seen = new Set<string>()
  for (let i = 0; i < positions.length; i += 3) {
    seen.add(`${q(positions[i])},${q(positions[i + 1])},${q(positions[i + 2])}`)
  }
  return createHash('sha256').update([...seen].sort().join('|')).digest('hex')
}

test('the 75-pocket reference tray matches the checked-in geometry fixture', () => {
  const mesh = buildTrayMesh(systainerTray())
  const report = checkManifold(mesh)

  assert.equal(mesh.triangleCount, fixture.triangleCount, 'triangle count moved')
  assert.equal(mesh.positions.length / 3, fixture.vertexCount, 'vertex count moved')
  assert.deepEqual(mesh.bbox.map(v => +v.toFixed(4)), fixture.bbox, 'footprint moved')
  assert.equal(report.danglingEdges, 0)
  assert.ok(
    Math.abs(report.volume - fixture.volumeMm3) / fixture.volumeMm3 < 1e-9,
    `volume ${report.volume} vs fixture ${fixture.volumeMm3}`,
  )
  assert.equal(vertexSetHash(mesh.positions), fixture.vertexSetSha256, 'vertex set moved')
})

test('the reference tray writes an STL of exactly the fixture size', () => {
  const mesh = buildTrayMesh(systainerTray())
  const stl = writeBinaryStl(mesh, 'ShapePilot reference tray')
  assert.equal(stl.byteLength, fixture.stlBytes)
  assert.equal(stl.byteLength, 84 + 50 * mesh.triangleCount)
})
