// Build the trace calibration sheet.
//
// `docs/trace-calibration-sheet.html` is GENERATED by this script rather than
// hand-written, because every number on it is load-bearing: the four targets
// have to sit on the corners of an exactly known rectangle, and a grid drawn by
// hand is a grid with a typo in it somewhere. Edit the constants here and
// re-run; do not edit the HTML.
//
//   node scripts/build-calibration-sheet.ts     # writes the HTML
//   npm run calibration:render                  # HTML -> committed PDF
//
// The PDF is what anybody actually prints. Browsers apply their own print
// scaling far too eagerly, and a sheet that is silently 96% of the size it
// claims is worse than no sheet at all -- it produces confident, wrong numbers.
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

/** US Letter, in millimetres. Everything below is mm. */
const PAGE_W = 215.9
const PAGE_H = 279.4

/**
 * The registration rectangle: the distance between opposite targets, and the
 * only measurement the maths actually depends on.
 *
 * 180 x 240 rather than the 8 x 10 inches (203.2 x 254) originally asked for,
 * for a dull reason: 8 x 10 centred on Letter leaves 6.35 mm margins, and most
 * laser printers cannot lay toner within 5-6 mm of the edge. A target clipped
 * by the printer's own dead zone is a sheet that silently loses a corner. This
 * leaves 17.95 mm at the sides and 19.7 mm top and bottom, and it also fits A4
 * (15 mm sides, 28.5 top and bottom) so one sheet serves both.
 *
 * 180 x 240 is also a 3-4-5 triangle, so the diagonal is exactly 300.00 mm.
 * That is a free third calibration length, and the useful one: two axis
 * measurements agree happily on a sheet that has been printed with a shear,
 * and the diagonal is what catches it.
 */
const RECT_W = 180
const RECT_H = 240
const ORIGIN_X = (PAGE_W - RECT_W) / 2
const ORIGIN_Y = (PAGE_H - RECT_H) / 2

/** The full scale, and the baseline a steel rule or tape reads end to end. */
const RULER_MM = 150

/**
 * The pair of marks a CALIPER measures, inset from the ruler's ends.
 *
 * 100.00 mm, not the ruler's own 150, and the reason is embarrassing: the
 * commonest caliper is a 150 mm one, so a 150 mm baseline sits at the exact
 * limit of its range with nothing left to register against. The first person to
 * print this sheet reached for a bench rule instead, which is the tell. 100 mm
 * is comfortably inside any caliper and still a long enough baseline that 0.1 mm
 * of reading error is 0.1% of scale.
 *
 * Two lengths per axis is not redundant either: 150 and 100 measured together
 * say whether the error is proportional, which is what a scale factor can fix,
 * or a fixed offset, which it cannot.
 */
const CALIPER_MM = 100

/**
 * The dark panel, for light-coloured parts.
 *
 * A white tube on white paper has almost no edge to find: the only thing
 * separating part from sheet is a shadow, and a shadow falls on one side, is
 * soft, and reads as part of the object. On black the edge is unambiguous all
 * the way round and the shadow stops mattering.
 *
 * This costs nothing in accuracy, which is the non-obvious part: the grid is
 * decorative as far as the maths is concerned, and only the four corner targets
 * are ever measured. So the middle of the sheet can be anything at all.
 *
 * Centred on the target rectangle rather than filling the space available,
 * because the centre is where parallax is zero -- an off-centre panel would
 * quietly invite the part to sit where the error is worst. Its size is the
 * largest symmetric box that still clears every target keep-out and both
 * rulers, asserted below rather than trusted.
 */
const PANEL_CLEAR_LEFT = 30
const PANEL_CLEAR_RIGHT = 14
const PANEL_CLEAR_TOP = 16
const PANEL_CLEAR_BOTTOM = 26

const GRID_FINE = 5
const GRID_BOLD = 10
const GRID_HEAVY = 50

const f = (n: number): string => Number(n.toFixed(4)).toString()

/**
 * A bullseye centred exactly on a rectangle corner.
 *
 * A ring plus a cross plus a small solid centre: the ring survives being
 * slightly out of focus, the cross gives two orthogonal edges to judge against,
 * and the dot is what you actually click. An L-bracket was the other candidate
 * and is worse to click -- its corner is inferred from two lines rather than
 * marked.
 */
const target = (cx: number, cy: number): string => `
    <g>
      <circle cx="${f(cx)}" cy="${f(cy)}" r="6" fill="#fff" stroke="#000" stroke-width="0.6"/>
      <circle cx="${f(cx)}" cy="${f(cy)}" r="3.2" fill="none" stroke="#000" stroke-width="0.5"/>
      <line x1="${f(cx - 8.5)}" y1="${f(cy)}" x2="${f(cx + 8.5)}" y2="${f(cy)}"
            stroke="#000" stroke-width="0.35"/>
      <line x1="${f(cx)}" y1="${f(cy - 8.5)}" x2="${f(cx)}" y2="${f(cy + 8.5)}"
            stroke="#000" stroke-width="0.35"/>
      <circle cx="${f(cx)}" cy="${f(cy)}" r="0.9" fill="#000"/>
    </g>`

/** Grid lines at one pitch, clipped to the rectangle. */
const grid = (pitch: number, stroke: string, width: number): string => {
  const parts: string[] = []
  for (let x = 0; x <= RECT_W + 1e-9; x += pitch) {
    parts.push(`<line x1="${f(ORIGIN_X + x)}" y1="${f(ORIGIN_Y)}" `
      + `x2="${f(ORIGIN_X + x)}" y2="${f(ORIGIN_Y + RECT_H)}"/>`)
  }
  for (let y = 0; y <= RECT_H + 1e-9; y += pitch) {
    parts.push(`<line x1="${f(ORIGIN_X)}" y1="${f(ORIGIN_Y + y)}" `
      + `x2="${f(ORIGIN_X + RECT_W)}" y2="${f(ORIGIN_Y + y)}"/>`)
  }
  return `    <g stroke="${stroke}" stroke-width="${f(width)}" fill="none">\n      `
    + parts.join('\n      ') + '\n    </g>'
}

/**
 * A ruler with hard end marks, meant to be measured with calipers rather than
 * read by eye. The end marks are the measurement; the ticks are orientation.
 */
const ruler = (
  x: number, y: number, length: number, vertical: boolean,
): string => {
  const parts: string[] = []
  const along = (d: number): [number, number] => vertical ? [x, y + d] : [x + d, y]
  const across = (px: number, py: number, d: number): [number, number] =>
    vertical ? [px + d, py] : [px, py + d]

  for (let d = 0; d <= length + 1e-9; d += 1) {
    const major = Math.abs(d % 10) < 1e-9
    const mid = Math.abs(d % 5) < 1e-9
    const len = major ? 4 : mid ? 2.6 : 1.4
    const [ax, ay] = along(d)
    const [bx, by] = across(ax, ay, len)
    parts.push(`<line x1="${f(ax)}" y1="${f(ay)}" x2="${f(bx)}" y2="${f(by)}" `
      + `stroke="#000" stroke-width="${major ? 0.3 : 0.18}"/>`)
    if (major && d > 0 && d < length) {
      const [tx, ty] = across(ax, ay, len + 3.2)
      parts.push(`<text x="${f(tx)}" y="${f(ty)}" font-size="3" text-anchor="middle" `
        + `fill="#000">${d}</text>`)
    }
  }
  // The rule baseline: the full span, end to end, heavier than anything near it.
  for (const d of [0, length]) {
    const [ax, ay] = along(d)
    const [bx, by] = across(ax, ay, -2.5)
    parts.push(`<line x1="${f(ax)}" y1="${f(ay)}" x2="${f(bx)}" y2="${f(by)}" `
      + `stroke="#000" stroke-width="0.7"/>`)
  }
  // The caliper baseline: a solid triangle either side, points facing in, so a
  // jaw has a physical edge to seat against rather than the middle of a line.
  const inset = (length - CALIPER_MM) / 2
  for (const d of [inset, length - inset]) {
    const [ax, ay] = along(d)
    const tip = across(ax, ay, -0.4)
    const w = 1.5
    const back = across(ax, ay, -3.2)
    const [b1x, b1y] = vertical ? [back[0], back[1] - w] : [back[0] - w, back[1]]
    const [b2x, b2y] = vertical ? [back[0], back[1] + w] : [back[0] + w, back[1]]
    parts.push(`<polygon points="${f(tip[0])},${f(tip[1])} ${f(b1x)},${f(b1y)} `
      + `${f(b2x)},${f(b2y)}" fill="#000"/>`)
  }
  return parts.join('\n      ')
}

const cx = ORIGIN_X + RECT_W / 2
const cy = ORIGIN_Y + RECT_H / 2

const halfW = Math.min(
  cx - (ORIGIN_X + PANEL_CLEAR_LEFT), (ORIGIN_X + RECT_W - PANEL_CLEAR_RIGHT) - cx)
const halfH = Math.min(
  cy - (ORIGIN_Y + PANEL_CLEAR_TOP), (ORIGIN_Y + RECT_H - PANEL_CLEAR_BOTTOM) - cy)
const PANEL = { x0: cx - halfW, y0: cy - halfH, x1: cx + halfW, y1: cy + halfH }

/**
 * Nothing measurable may end up under the panel, and a proof will not show it:
 * black ink on a black rectangle is invisible. So it is asserted at build time.
 *
 * The keep-outs are what each feature actually OCCUPIES, not the line it is
 * drawn from -- the vertical ruler's numbers sit 7 mm to the right of its rule
 * and its caption 5 mm to the left, so guarding the rule alone guards nothing.
 * MARGIN then demands real clearance rather than mere non-overlap: the first
 * version of this check compared against the bare rule and passed a panel whose
 * edge landed on it exactly, losing to floating point by 1.4e-14.
 */
const MARGIN = 2
interface Box { x0: number; y0: number; x1: number; y1: number }
const KEEP_OUT: [string, Box][] = [
  ...([
    [ORIGIN_X, ORIGIN_Y], [ORIGIN_X + RECT_W, ORIGIN_Y],
    [ORIGIN_X + RECT_W, ORIGIN_Y + RECT_H], [ORIGIN_X, ORIGIN_Y + RECT_H],
  ] as const).map(([tx, ty]): [string, Box] => [
    `target ${tx},${ty}`,
    { x0: tx - 8.5, y0: ty - 8.5, x1: tx + 8.5, y1: ty + 8.5 },
  ]),
  ['the ruler down the page', {
    x0: ORIGIN_X + 5, y0: ORIGIN_Y, x1: ORIGIN_X + 23, y1: ORIGIN_Y + RECT_H,
  }],
  ['the ruler across the page', {
    x0: ORIGIN_X, y0: ORIGIN_Y + RECT_H - 19,
    x1: ORIGIN_X + RECT_W, y1: ORIGIN_Y + RECT_H - 7,
  }],
]
for (const [what, box] of KEEP_OUT) {
  const clash = PANEL.x0 < box.x1 + MARGIN && box.x0 - MARGIN < PANEL.x1
    && PANEL.y0 < box.y1 + MARGIN && box.y0 - MARGIN < PANEL.y1
  if (clash) throw new Error(`the dark panel comes within ${MARGIN} mm of ${what}`)
}

const lightZone = (): string => `  <g>
    <circle cx="${f(cx)}" cy="${f(cy)}" r="55" fill="none" stroke="#b0b6bb"
            stroke-width="0.4" stroke-dasharray="3 2.5"/>
    <text x="${f(cx)}" y="${f(cy - 58)}" font-size="3.4" text-anchor="middle" fill="#6d747a">
      PUT THE PART HERE — centred, flattest face down
    </text>
  </g>`

/**
 * Solid, and deliberately unmarked. No grid over it, no centre cross, nothing:
 * every line printed inside this rectangle is an edge a tracer can mistake for
 * the part. Centring instead gets four ticks OUTSIDE the panel, on the white,
 * where they help the eye and never reach the silhouette.
 */
const darkPanel = (): string => {
  const t = 4
  const ticks = [
    `<line x1="${f(cx)}" y1="${f(PANEL.y0 - t)}" x2="${f(cx)}" y2="${f(PANEL.y0 - 0.8)}"/>`,
    `<line x1="${f(cx)}" y1="${f(PANEL.y1 + 0.8)}" x2="${f(cx)}" y2="${f(PANEL.y1 + t)}"/>`,
    `<line x1="${f(PANEL.x0 - t)}" y1="${f(cy)}" x2="${f(PANEL.x0 - 0.8)}" y2="${f(cy)}"/>`,
    `<line x1="${f(PANEL.x1 + 0.8)}" y1="${f(cy)}" x2="${f(PANEL.x1 + t)}" y2="${f(cy)}"/>`,
  ].join('\n      ')
  return `  <g>
    <rect x="${f(PANEL.x0)}" y="${f(PANEL.y0)}" width="${f(PANEL.x1 - PANEL.x0)}"
          height="${f(PANEL.y1 - PANEL.y0)}" fill="#000"/>
    <g stroke="#16181a" stroke-width="0.4">
      ${ticks}
    </g>
    <text x="${f(cx)}" y="${f(PANEL.y0 - 6.5)}" font-size="3.4" text-anchor="middle" fill="#6d747a">
      PUT THE PART ON THE BLACK — centred between the ticks, flattest face down
    </text>
  </g>`
}

const buildSvg = (dark: boolean): string => `<svg xmlns="http://www.w3.org/2000/svg"
     width="${f(PAGE_W)}mm" height="${f(PAGE_H)}mm"
     viewBox="0 0 ${f(PAGE_W)} ${f(PAGE_H)}"
     shape-rendering="crispEdges">
  <rect x="0" y="0" width="${f(PAGE_W)}" height="${f(PAGE_H)}" fill="#fff"/>

${grid(GRID_FINE, '#c9ced3', 0.12)}
${grid(GRID_BOLD, '#9aa2a9', 0.2)}
${grid(GRID_HEAVY, '#6d747a', 0.35)}

  <rect x="${f(ORIGIN_X)}" y="${f(ORIGIN_Y)}" width="${f(RECT_W)}" height="${f(RECT_H)}"
        fill="none" stroke="#3c4145" stroke-width="0.4"/>

  <!-- The place-it-here zone. Dead centre, because parallax is zero only
       under the lens and grows with distance from it. -->
${dark ? darkPanel() : lightZone()}

  <!-- Targets on the rectangle corners. -->
${target(ORIGIN_X, ORIGIN_Y)}
${target(ORIGIN_X + RECT_W, ORIGIN_Y)}
${target(ORIGIN_X + RECT_W, ORIGIN_Y + RECT_H)}
${target(ORIGIN_X, ORIGIN_Y + RECT_H)}

  <!-- Orientation key: one filled square, top-left only, so a photo taken
       upside down or mirrored cannot be silently rectified the wrong way. -->
  <rect x="${f(ORIGIN_X + 9)}" y="${f(ORIGIN_Y + 9)}" width="5" height="5" fill="#000"/>
  <text x="${f(ORIGIN_X + 16.5)}" y="${f(ORIGIN_Y + 13.2)}" font-size="3" fill="#6d747a">
    TOP LEFT
  </text>

  <!-- Both axes get their own baseline: printers stretch differently along the
       feed direction than across the carriage, so one number cannot cover it. -->
  <g>
      ${ruler(cx - RULER_MM / 2, ORIGIN_Y + RECT_H - 14, RULER_MM, false)}
    <text x="${f(cx)}" y="${f(ORIGIN_Y + RECT_H - 17)}" font-size="3.2"
          text-anchor="middle" fill="#16181a">
      CALIPER, triangle to triangle = ${CALIPER_MM}.00 mm   ·   RULE, bar to bar = ${RULER_MM}.00 mm
    </text>
  </g>
  <g>
      ${ruler(ORIGIN_X + 14, cy - RULER_MM / 2, RULER_MM, true)}
    <text x="${f(ORIGIN_X + 8.5)}" y="${f(cy)}" font-size="3.2" fill="#16181a"
          transform="rotate(-90 ${f(ORIGIN_X + 8.5)} ${f(cy)})" text-anchor="middle">
      CALIPER, triangle to triangle = ${CALIPER_MM}.00   ·   RULE, bar to bar = ${RULER_MM}.00
    </text>
  </g>

  <!-- Everything needed to reprint it correctly, on the sheet itself.
       Indented past the corner targets: prose flush with the rectangle runs
       straight through the two left-hand bullseyes, and a target with a
       sentence across it is a target you cannot click accurately. -->
  <g fill="#3c4145" font-size="3.1">
    <text x="${f(ORIGIN_X + 12)}" y="${f(ORIGIN_Y - 12.2)}" font-size="4.2" fill="#16181a">
      ShapePilot trace calibration sheet${dark ? ' · dark centre' : ''} — targets ${RECT_W} × ${RECT_H} mm
    </text>
    <text x="${f(ORIGIN_X + 12)}" y="${f(ORIGIN_Y - 7.6)}">
      PRINT AT 100% — no fit-to-page, no shrink-to-fit, no borderless.
    </text>
    <text x="${f(ORIGIN_X + 12)}" y="${f(ORIGIN_Y - 3.4)}">
      Measure first: triangles ${CALIPER_MM}.00 mm apart, end bars ${RULER_MM}.00, target diagonal exactly 300.00 mm.
    </text>
  </g>
  <g fill="#3c4145" font-size="3.1">
    <text x="${f(ORIGIN_X + 12)}" y="${f(ORIGIN_Y + RECT_H + 5.6)}">
      SHOOT: directly overhead, part centred, all four targets in frame. Zoom in rather than moving closer.
    </text>
    <text x="${f(ORIGIN_X + 12)}" y="${f(ORIGIN_Y + RECT_H + 9.9)}">
      Diffuse light. No flash, and no shadow lying across an edge that matters.
    </text>
    <text x="${f(ORIGIN_X + 12)}" y="${f(ORIGIN_Y + RECT_H + 14.2)}">
      Measure the part's HEIGHT too: 20 mm tall, 100 mm off centre, traces ~5 mm oversize uncorrected.
    </text>
    <text x="${f(ORIGIN_X + 12)}" y="${f(ORIGIN_Y + RECT_H + 18.5)}">
      ${dark
        ? 'Black is for pale parts. Only the four targets are ever measured, so the middle of the sheet can be anything.'
        : 'Pale or shiny part on white paper has no edge to find — use the dark-centre sheet for those.'}
    </text>
  </g>
</svg>`

const buildHtml = (dark: boolean): string => `<!--
  ShapePilot trace calibration sheet.

  GENERATED by scripts/build-calibration-sheet.ts -- do not edit this file.
  Every dimension here is load-bearing; edit the constants in the script and
  re-run, then re-render the PDF with \`npm run calibration:render\`.

  The PDF beside it is the artefact to print. Print the PDF at 100% scale.
-->
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>ShapePilot trace calibration sheet${dark ? ' (dark centre)' : ''}</title>
<style>
  @page { size: ${f(PAGE_W)}mm ${f(PAGE_H)}mm; margin: 0; }
  html, body { margin: 0; padding: 0; background: #fff; }
  svg { display: block; }
  text { font-family: ui-sans-serif, -apple-system, "Helvetica Neue", Arial, sans-serif; }
</style>
</head>
<body>
${buildSvg(dark)}
</body>
</html>
`

for (const dark of [false, true]) {
  const name = dark ? 'trace-calibration-sheet-dark.html' : 'trace-calibration-sheet.html'
  const output = resolve(import.meta.dirname, '..', 'docs', name)
  writeFileSync(output, buildHtml(dark))
  console.log(`wrote ${output}`)
}
console.log(`targets ${RECT_W} x ${RECT_H} mm, caliper ${CALIPER_MM}, rule ${RULER_MM}`)
console.log(`dark panel ${f(PANEL.x1 - PANEL.x0)} x ${f(PANEL.y1 - PANEL.y0)} mm, centred`)
