// Build the trace calibration sheet.
//
// `docs/trace-calibration-sheet.html` is GENERATED by this script rather than
// hand-written, because every number on it is load-bearing: the four targets
// have to sit on the corners of an exactly known rectangle, and a grid drawn by
// hand is a grid with a typo in it somewhere. Edit the constants here and
// re-run; do not edit the HTML.
//
//   node scripts/build-calibration-sheet.ts     # writes the HTML
//   npm run calibration:render                  # HTML -> committed PDF
//
// The PDF is what anybody actually prints. Browsers apply their own print
// scaling far too eagerly, and a sheet that is silently 96% of the size it
// claims is worse than no sheet at all -- it produces confident, wrong numbers.
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

/** US Letter, in millimetres. Everything below is mm. */
const PAGE_W = 215.9
const PAGE_H = 279.4

/**
 * The registration rectangle: the distance between opposite targets, and the
 * only measurement the maths actually depends on.
 *
 * 180 x 240 rather than the 8 x 10 inches (203.2 x 254) originally asked for,
 * for a dull reason: 8 x 10 centred on Letter leaves 6.35 mm margins, and most
 * laser printers cannot lay toner within 5-6 mm of the edge. A target clipped
 * by the printer's own dead zone is a sheet that silently loses a corner. This
 * leaves 17.95 mm at the sides and 19.7 mm top and bottom, and it also fits A4
 * (15 mm sides, 28.5 top and bottom) so one sheet serves both.
 *
 * 180 x 240 is also a 3-4-5 triangle, so the diagonal is exactly 300.00 mm.
 * That is a free third calibration length, and the useful one: two axis
 * measurements agree happily on a sheet that has been printed with a shear,
 * and the diagonal is what catches it.
 */
const RECT_W = 180
const RECT_H = 240
const ORIGIN_X = (PAGE_W - RECT_W) / 2
const ORIGIN_Y = (PAGE_H - RECT_H) / 2

/** The calipered baselines. Longer is better: the error is proportional. */
const RULER_MM = 150

const GRID_FINE = 5
const GRID_BOLD = 10
const GRID_HEAVY = 50

const f = (n: number): string => Number(n.toFixed(4)).toString()

/**
 * A bullseye centred exactly on a rectangle corner.
 *
 * A ring plus a cross plus a small solid centre: the ring survives being
 * slightly out of focus, the cross gives two orthogonal edges to judge against,
 * and the dot is what you actually click. An L-bracket was the other candidate
 * and is worse to click -- its corner is inferred from two lines rather than
 * marked.
 */
const target = (cx: number, cy: number): string => `
    <g>
      <circle cx="${f(cx)}" cy="${f(cy)}" r="6" fill="#fff" stroke="#000" stroke-width="0.6"/>
      <circle cx="${f(cx)}" cy="${f(cy)}" r="3.2" fill="none" stroke="#000" stroke-width="0.5"/>
      <line x1="${f(cx - 8.5)}" y1="${f(cy)}" x2="${f(cx + 8.5)}" y2="${f(cy)}"
            stroke="#000" stroke-width="0.35"/>
      <line x1="${f(cx)}" y1="${f(cy - 8.5)}" x2="${f(cx)}" y2="${f(cy + 8.5)}"
            stroke="#000" stroke-width="0.35"/>
      <circle cx="${f(cx)}" cy="${f(cy)}" r="0.9" fill="#000"/>
    </g>`

/** Grid lines at one pitch, clipped to the rectangle. */
const grid = (pitch: number, stroke: string, width: number): string => {
  const parts: string[] = []
  for (let x = 0; x <= RECT_W + 1e-9; x += pitch) {
    parts.push(`<line x1="${f(ORIGIN_X + x)}" y1="${f(ORIGIN_Y)}" `
      + `x2="${f(ORIGIN_X + x)}" y2="${f(ORIGIN_Y + RECT_H)}"/>`)
  }
  for (let y = 0; y <= RECT_H + 1e-9; y += pitch) {
    parts.push(`<line x1="${f(ORIGIN_X)}" y1="${f(ORIGIN_Y + y)}" `
      + `x2="${f(ORIGIN_X + RECT_W)}" y2="${f(ORIGIN_Y + y)}"/>`)
  }
  return `    <g stroke="${stroke}" stroke-width="${f(width)}" fill="none">\n      `
    + parts.join('\n      ') + '\n    </g>'
}

/**
 * A ruler with hard end marks, meant to be measured with calipers rather than
 * read by eye. The end marks are the measurement; the ticks are orientation.
 */
const ruler = (
  x: number, y: number, length: number, vertical: boolean,
): string => {
  const parts: string[] = []
  const along = (d: number): [number, number] => vertical ? [x, y + d] : [x + d, y]
  const across = (px: number, py: number, d: number): [number, number] =>
    vertical ? [px + d, py] : [px, py + d]

  for (let d = 0; d <= length + 1e-9; d += 1) {
    const major = Math.abs(d % 10) < 1e-9
    const mid = Math.abs(d % 5) < 1e-9
    const len = major ? 4 : mid ? 2.6 : 1.4
    const [ax, ay] = along(d)
    const [bx, by] = across(ax, ay, len)
    parts.push(`<line x1="${f(ax)}" y1="${f(ay)}" x2="${f(bx)}" y2="${f(by)}" `
      + `stroke="#000" stroke-width="${major ? 0.3 : 0.18}"/>`)
    if (major && d > 0 && d < length) {
      const [tx, ty] = across(ax, ay, len + 3.2)
      parts.push(`<text x="${f(tx)}" y="${f(ty)}" font-size="3" text-anchor="middle" `
        + `fill="#000">${d}</text>`)
    }
  }
  // The two lines that are the actual baseline, drawn heavier than anything
  // near them so a caliper jaw has something unambiguous to sit against.
  for (const d of [0, length]) {
    const [ax, ay] = along(d)
    const [bx, by] = across(ax, ay, -2.5)
    parts.push(`<line x1="${f(ax)}" y1="${f(ay)}" x2="${f(bx)}" y2="${f(by)}" `
      + `stroke="#000" stroke-width="0.7"/>`)
  }
  return parts.join('\n      ')
}

const cx = ORIGIN_X + RECT_W / 2
const cy = ORIGIN_Y + RECT_H / 2

const svg = `<svg xmlns="http://www.w3.org/2000/svg"
     width="${f(PAGE_W)}mm" height="${f(PAGE_H)}mm"
     viewBox="0 0 ${f(PAGE_W)} ${f(PAGE_H)}"
     shape-rendering="crispEdges">
  <rect x="0" y="0" width="${f(PAGE_W)}" height="${f(PAGE_H)}" fill="#fff"/>

${grid(GRID_FINE, '#c9ced3', 0.12)}
${grid(GRID_BOLD, '#9aa2a9', 0.2)}
${grid(GRID_HEAVY, '#6d747a', 0.35)}

  <rect x="${f(ORIGIN_X)}" y="${f(ORIGIN_Y)}" width="${f(RECT_W)}" height="${f(RECT_H)}"
        fill="none" stroke="#3c4145" stroke-width="0.4"/>

  <!-- The place-it-here zone. Dead centre, because parallax is zero only
       under the lens and grows with distance from it. -->
  <g>
    <circle cx="${f(cx)}" cy="${f(cy)}" r="55" fill="none" stroke="#b0b6bb"
            stroke-width="0.4" stroke-dasharray="3 2.5"/>
    <text x="${f(cx)}" y="${f(cy - 58)}" font-size="3.4" text-anchor="middle" fill="#6d747a">
      PUT THE PART HERE — centred, flattest face down
    </text>
  </g>

  <!-- Targets on the rectangle corners. -->
${target(ORIGIN_X, ORIGIN_Y)}
${target(ORIGIN_X + RECT_W, ORIGIN_Y)}
${target(ORIGIN_X + RECT_W, ORIGIN_Y + RECT_H)}
${target(ORIGIN_X, ORIGIN_Y + RECT_H)}

  <!-- Orientation key: one filled square, top-left only, so a photo taken
       upside down or mirrored cannot be silently rectified the wrong way. -->
  <rect x="${f(ORIGIN_X + 9)}" y="${f(ORIGIN_Y + 9)}" width="5" height="5" fill="#000"/>
  <text x="${f(ORIGIN_X + 16.5)}" y="${f(ORIGIN_Y + 13.2)}" font-size="3" fill="#6d747a">
    TOP LEFT
  </text>

  <!-- Both axes get their own baseline: printers stretch differently along the
       feed direction than across the carriage, so one number cannot cover it. -->
  <g>
      ${ruler(cx - RULER_MM / 2, ORIGIN_Y + RECT_H - 14, RULER_MM, false)}
    <text x="${f(cx)}" y="${f(ORIGIN_Y + RECT_H - 17)}" font-size="3.2"
          text-anchor="middle" fill="#16181a">
      CALIPER: heavy mark to heavy mark = ${RULER_MM}.00 mm across
    </text>
  </g>
  <g>
      ${ruler(ORIGIN_X + 14, cy - RULER_MM / 2, RULER_MM, true)}
    <text x="${f(ORIGIN_X + 8.5)}" y="${f(cy)}" font-size="3.2" fill="#16181a"
          transform="rotate(-90 ${f(ORIGIN_X + 8.5)} ${f(cy)})" text-anchor="middle">
      CALIPER: ${RULER_MM}.00 mm down the page
    </text>
  </g>

  <!-- Everything needed to reprint it correctly, on the sheet itself.
       Indented past the corner targets: prose flush with the rectangle runs
       straight through the two left-hand bullseyes, and a target with a
       sentence across it is a target you cannot click accurately. -->
  <g fill="#3c4145" font-size="3.1">
    <text x="${f(ORIGIN_X + 12)}" y="${f(ORIGIN_Y - 12.2)}" font-size="4.2" fill="#16181a">
      ShapePilot trace calibration sheet — targets ${RECT_W} × ${RECT_H} mm
    </text>
    <text x="${f(ORIGIN_X + 12)}" y="${f(ORIGIN_Y - 7.6)}">
      PRINT AT 100% — no fit-to-page, no shrink-to-fit, no borderless.
    </text>
    <text x="${f(ORIGIN_X + 12)}" y="${f(ORIGIN_Y - 3.4)}">
      Plain matte paper. Caliper both rulers first — target to target is ${RECT_W}×${RECT_H}, diagonal exactly 300.00 mm.
    </text>
  </g>
  <g fill="#3c4145" font-size="3.1">
    <text x="${f(ORIGIN_X + 12)}" y="${f(ORIGIN_Y + RECT_H + 5.6)}">
      SHOOT: directly overhead, part centred, all four targets in frame. Zoom in rather than moving closer.
    </text>
    <text x="${f(ORIGIN_X + 12)}" y="${f(ORIGIN_Y + RECT_H + 9.9)}">
      Diffuse light. No flash, and no shadow lying across an edge that matters.
    </text>
    <text x="${f(ORIGIN_X + 12)}" y="${f(ORIGIN_Y + RECT_H + 14.2)}">
      Measure the part's HEIGHT too: 20 mm tall, 100 mm off centre, traces ~5 mm oversize uncorrected.
    </text>
  </g>
</svg>`

const html = `<!--
  ShapePilot trace calibration sheet.

  GENERATED by scripts/build-calibration-sheet.ts -- do not edit this file.
  Every dimension here is load-bearing; edit the constants in the script and
  re-run, then re-render the PDF with \`npm run calibration:render\`.

  The PDF beside it is the artefact to print. Print the PDF at 100% scale.
-->
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>ShapePilot trace calibration sheet</title>
<style>
  @page { size: ${f(PAGE_W)}mm ${f(PAGE_H)}mm; margin: 0; }
  html, body { margin: 0; padding: 0; background: #fff; }
  svg { display: block; }
  text { font-family: ui-sans-serif, -apple-system, "Helvetica Neue", Arial, sans-serif; }
</style>
</head>
<body>
${svg}
</body>
</html>
`

const output = resolve(import.meta.dirname, '..', 'docs', 'trace-calibration-sheet.html')
writeFileSync(output, html)
console.log(`wrote ${output}`)
console.log(`targets ${RECT_W} x ${RECT_H} mm, rulers ${RULER_MM} mm, page ${PAGE_W} x ${PAGE_H} mm`)
